### ISSUE TITLE
Release process should not rename the css and js files

### ISSUE THREAD

**Issue by daonb** [Beit-Hatfutsot/dbs-front#110]
Today, with every release we create new file name s for css and js files. This causes returning user to receive a black page: their index.html includes references to the old names that no longer exist. 
To solve this issue we need to add the temporary name as a query parameter, i.e. Instead of `/scripts/741fc565.vendor.js` we should ling to `/scripts/vendor.js?v=741fc565`

**Comment by daonb** [comment]
@alonisser makes sense?

**Comment by alonisser** [comment]
No.. why would a return user get an empty page? unless you are doing some **wrong** caching somewhere for html pages.. using revved filenames is a best practice and I used it in lots of places. never encountered this problem.

What might be the **Real** problem: Html pages caching (a big no no) - this isn't client side (since browsers don't cache html) but can be in web server (nginx/apache) or in a cdn/protection layer like cloudflare/incapsula//akamai do you use any of them?

**Comment by daonb** [comment]
On the server we have an nginx with no caching and we don't use any CDN for now. I'll look at it closely in our next release, but for now, I'm closing this.

**Comment by alonisser** [comment]
Don't close yet. please send me nginx.conf (the main and the default.conf or something similar)

**Comment by alonisser** [comment]
Please notify me before and after the deploy so I can witness the effect my
self

**Comment by alonisser** [comment]
Also main.css looks double there.. Not sure where this come s from
