### ISSUE TITLE
Vainstein - Forbes Syndrome (name difference between search result and person in tree)

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-front#158]
A search result on this page:
http://dbs.bh.org.il/person?last_name=vainstein
name Jacobo Vainstein, when clicked on, magically turns into a Paul Forbes.
The rest of the data is unchanged - the tree number matches between the result and the inside of the tree.
The daughter is still Amy.

I will add more URLs with similar cases that match the syndrome as i find them.

**Comment by daonb** [comment]
The gedom we have for this tree is a bit different than the one that was loaded into BHP.  Our migration process merges info from the BHP and from a parsed Gedcom and that's why we find details from two different individuals in the same person.

Let's examine Jacobo/Vainstein/Paul Frobes as a n example. Based on the url - http://dbs.bh.org.il/person/231/I0339 - we know it's person id `I0339` in tree number `231`. Looking at PHP the name of this person is Jacobo Vainstein, but in the gedcom file it's Paul Forbes.

I can think oif two causes for this issue:
- the gedcoms we have are not up to date.
- one of the BHP editors have changed the names

As Haim assured me they never edit family trees, I assume we've been using outdated gedcom files. 

I am now looking for a fresher version of the file.

**Comment by daonb** [comment]
Found that this specific tree has 4 versions: from 2006, 2007,2008 an done from 2010. The one we're parsing as part of the migration is the one from 2006 :-(

**Comment by TheGrandVizier** [comment]
This issue was moved to Beit-Hatfutsot/dbs-back#20
