### ISSUE TITLE
General search freezes browser, breaks results page.

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-front#314]
After using general search, the following takes place:

1. The browser freezes.
2. Many objects are unclickable.
3. Using the result tabs causes freezes to the browser.
4. The main site tabs are broken: http://prntscr.com/eec7e5
5. Item pages load with footer in the middle of the page: http://prntscr.com/eec7mw

Reproduce:
1. enter test.dbs.bh.org.il
2. use general search, search for anything.

**Comment by Inna-r** [comment]
@OriHoch , there is "WARNING: Tried to load angular more than once."  in the console

**Comment by OriHoch** [comment]
@Inna-r - the problem is that the svg files are not in the correct place for static files, so the server returns the 404 page when making a request to svg file and this causes the entire app to reload multiple times

for example - 
http://test.dbs.bh.org.il/templates/svgs/family_names.svg

the files should be in images directory, or alternatively, modify the gulpfile to support the proper distribution of those files

**Comment by OriHoch** [comment]
you can test the server distribution locally by running:
`$ gulp dist`

this creates dist directory which contains the files that are on the server, you can then serve them locally, e.g. using python:
`$ cd dist`
`dist$ python -m SimpleHTTPServer`

**Comment by TheGrandVizier** [comment]
Tested, fixed.

**Comment by OriHoch** [comment]
nice, thanks
it's in draft release 0.11.2
