### ISSUE TITLE
"Home" button from item page leeds to HEB HP

### ISSUE THREAD

**Issue by Libisch** [Beit-Hatfutsot/dbs-front#327]
**+** While on HEB HP, hitting "back" on explorer changes the URL from the original item page, for example:
`http://test.dbs.bh.org.il/familyname/cohen`
to 
`http://test.dbs.bh.org.il/person?last_name=COHEN`

**Comment by Libisch** [comment]
@TheGrandVizier I'm not sure these issues are connected.

**Comment by OriHoch** [comment]
the issue was not reproduced for me, here are the steps I did, let me know if I misunderstood something:

#### reproduction steps
* open http://test.dbs.bh.org.il/
* click on "search", type "cohen" and search
* on the search results page, click on the first result (cohen family name)
* click on "HE" to switch to hebrew
* click on "ראשי" to go to heb homepage
* click the browser back button

##### expected
* go back hebrew Cohen item page

#####
* as expected

**Comment by Libisch** [comment]
Works for me too now.

**Comment by TheGrandVizier** [comment]
Closing for being imaginary
