### ISSUE TITLE
Item page displays faulty link to family tree where it shouldnt

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-front#331]
Arriving at any page from general search results, there is a faulty link to a family tree that should not be there on the top right of the page:
http://prntscr.com/emmgfh

Reproduce:
1. Use general search: Cohen
2. Click on any result.

Expected result: 
Item page with no attached / "docked" items.

Actual result: 
Item page with "docked" family tree link that doesnt leads to person search.

Note: This type of link should only exist for results originating in wizard.

**Comment by OriHoch** [comment]
@TheGrandVizier - is this a regression? or an existing bug? It doesn't look like something caused by the deployment

**Comment by TheGrandVizier** [comment]
I believe its regression. This doesn't occur on test.

**Comment by OriHoch** [comment]
ok, I'll investigate

**Comment by OriHoch** [comment]
most likely is that it's a local bug which only you see due to some data left in your session storage

you should try to clear it by typing in console `sessionStorage.clear()`:
![image](https://cloud.githubusercontent.com/assets/1198854/24146474/92ceb2de-0e3e-11e7-863f-19f6f38f4df0.png)

then see if it reproduces..

I don't think it's worth to investigate much further, it's likely it happens to you because you saw a lot of bugs which might have stored some problematic data in your session storage.

regarding your note that it shouldn't even appear - please open in a new issue

**Comment by TheGrandVizier** [comment]
Yea, my bad, false flag. How noob of me. Apologies.
