### ISSUE TITLE
general search suggestions: confusing behavior when choosing suggest under a section

### ISSUE THREAD

**Issue by OriHoch** [Beit-Hatfutsot/dbs-front#377]
### reproduction steps
* type "Berlin" in search box (don't search)
* look at the suggestions
* 
![image](https://cloud.githubusercontent.com/assets/1198854/26093757/da80289e-3a1f-11e7-9219-782e15eced81.png)
* click on "Berlin" under "People" section

#### expected
* see People named "Berlin"
* that's at least what I'm expecting, maybe I'm wrong.. this is possibly a UX issue

#### actual
* see all results for "Berlin"
* 
![image](https://cloud.githubusercontent.com/assets/1198854/26093812/0d728800-3a20-11e7-9b2d-17caacaef66b.png)

**Comment by OriHoch** [comment]
### alternative solution
* don't show sections in the suggestions box - just show all suggestions combined - then this behavior will make sense (to me..)

**Comment by OriHoch** [comment]
another example:
* type "בלה כהן" in search box
* choose the first suggestion for "בלה כהן" under People title
* **expected**: see בלה כהן
* **actual**: 
![image](https://cloud.githubusercontent.com/assets/1198854/26094336/424a6ac8-3a22-11e7-81b9-a0786456c708.png)

**Comment by nuritgazit** [comment]
I don't think your suggestion, @OriHoch, will solve the problem, because people can still search for people and get to different search results, only they won't know it.
There is a UX Solution that @Netush is already working on, I've asked her to step on it. When she is done we can review it and estimate the effort. Till then we can't push this to production.

**Comment by TheGrandVizier** [comment]
Feature was canceled
