### ISSUE TITLE
Remove General Search Suggestions

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-front#387]
It has been decided this feature needs to leave.

Repro:
1. Search for Moscow in general search

Actual:
1. As you type, suggestion box appears and makes suggestions

Expected:
1. Nothing changes until user finishes input and presses enter (or search).

**Comment by OriHoch** [comment]
@TheGrandVizier @Netush @nuritgazit - please explain the reasoning behind this..

**Comment by nuritgazit** [comment]
I think we can define the reason to *do* it in the first place as a twist in our product sobriety.
In other words, we got confused due to our wish to make the behavior of the 3 search engines as close, if not identical, as possible.
In other words, we now understand that providing suggestions which are exact items from the DBs will limit the user more than it will help him. It is less so in short-titled items such as family names and places, but more so in long-titled items such as images or names of people in trees.
This is opposed to provide suggestions which are based on "synonyms" and/or "sounds like" and/or auto-completion of search terms done by other people in big numbers, which should be discussed and defined. Till then, the General search should stay suggestionless.

**Comment by OriHoch** [comment]
thanks, makes sense and good thing we caught it now before it was deployed

**Comment by OriHoch** [comment]
@Inna-r seems easy to do, I would suggest to do it at the highest priority
