### ISSUE TITLE
Investigate the *

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-front#389]
SEO data indicates there are searches being done with * as the only term.

This is not possible via the front end proper as General search requires at least 2 characters to initiate a search.

I have only been able to reproduce this by manipulating the URL by changing:
`http://test.dbs.bh.org.il/search?q=moscow`
into
`http://test.dbs.bh.org.il/search?q=*`

- [ ] Investigate if it is possible to produce that without URL manipulation

- [ ] Disallow such searching (*) ("everything").

**Comment by OriHoch** [comment]
@TheGrandVizier  
how many such searches per time period? link to the SEO data will be helpful

**Comment by nuritgazit** [comment]
Check it out in the report [here](https://analytics.google.com/analytics/web/?authuser=1#dashboard/X2A4An4GSM6knM4786IqPA/a8676522w16472983p105292199/%3F_u.date00%3D20170401%26_u.date01%3D20170423/)

**Comment by Libisch** [comment]
@TheGrandVizier @OriHoch @nuritgazit This is caused by users clicking a link [here](http://www.bh.org.il/he/%D7%9E%D7%90%D7%92%D7%A8%D7%99%D7%9D-%D7%95%D7%90%D7%95%D7%A1%D7%A4%D7%99%D7%9D/%D7%A9%D7%9E%D7%95%D7%AA-%D7%9E%D7%A9%D7%A4%D7%97%D7%94/%D7%9E%D7%90%D7%92%D7%A8-%D7%A9%D7%9E%D7%95%D7%AA-%D7%94%D7%9E%D7%A9%D7%A4%D7%97%D7%94-%D7%9E%D7%91%D7%95%D7%90/), which I added some time ago, in order to use the traffic. 
<img width="497" alt="screen shot 2017-05-21 at 14 56 46" src="https://cloud.githubusercontent.com/assets/20017334/26283710/c3ee7b84-3e35-11e7-9314-0de1343de458.png">


Should the link be removed?

**Comment by nuritgazit** [comment]
@Libisch not at all, I will just let Daniel know, so that we count it as traffic coming from the old pages

**Comment by Libisch** [comment]
@nuritgazit It's weird he doesn't know, it's clear once checking 'previous page path'

<img width="608" alt="screen shot 2017-05-21 at 15 24 54" src="https://cloud.githubusercontent.com/assets/20017334/26283963/b7f370f6-3e39-11e7-8d15-ef5bcc8cd50c.png">

**Comment by Netush** [comment]
@nuritgazit should let Daniel know

**Comment by nuritgazit** [comment]
Updated Daniel and waiting for him to update the report so that it doesn't display "*" but instead the actual names of the pages from which the traffic gets to the DBs.
